SIDES/Areas/UI_SIDES/Controllers/SidesAttachmentsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Hosting.Internal;
using SIDES.EFCoreModels.ScafffoldEntities.Persistance;
using SIDES.Interface;
using SIDES.ViewModels;
using System.Diagnostics;
using System.Net;
using System.Net.Mail;
using System.Runtime.CompilerServices;
using System.Text;

namespace SIDES.Areas.UI_SIDES.Controllers
{
    [Area("UI_SIDES")]
    public class SidesAttachmentsController : Controller
    {
        private UCAContext _UCAContext;
        private ISidesTPARequest _TPARequest;
        private readonly IFlagRequestStatus flagRequestStatus;
        private IWebHostEnvironment _hostingEnvironment;

        public SidesAttachmentsController(UCAContext uCAContext, IWebHostEnvironment hostingEnvironment, ISidesTPARequest TPARequest, IFlagRequestStatus flagRequestStatus)
        {
            this._UCAContext = uCAContext;
            this._TPARequest = TPARequest;
            this.flagRequestStatus = flagRequestStatus;
            this._hostingEnvironment = hostingEnvironment;
        }

        [HttpGet]
        [Route("UI_SIDES/SidesAttachments/SidesAttachmentsV/{RSID}")]
        public IActionResult SidesAttachmentsV(int RSID)
        {
            try
            {

                var attachmentsModel = GetAttachmentsDetails(RSID);
                return View(attachmentsModel);
            }
            catch (Exception ex)
            {
                return View("Error");
            }

        }

        [HttpPost]
        [Route("UI_SIDES/SidesAttachments/SidesAttachmentsV/{RSID}")]
        public IActionResult SidesAttachmentsV(int RSID, string Save, string Next, string view, string delete, Attachments model, IFormFile AttachmentUpload)
        {
            try
            {
                if (!string.IsNullOrEmpty(Save))
                {
                    AttachmentSaveDetails(RSID, AttachmentUpload);
                    flagRequestStatus.FlagRequestStatus(RSID, "Pending");

                }
                if (!string.IsNullOrEmpty(Next))
                {

                    AttachmentSaveDetails(RSID, AttachmentUpload);
                    flagRequestStatus.FlagRequestStatus(RSID, "Pending");
                    //  return Redirect("https://localhost:44389/ui_sides/sidesPrepare/sidesPrepareV/" + RSID);
                    return RedirectToAction("sidesPrepareV", "sidesPrepare", new { id = RSID, Area = "UI_SIDES" });
                }
                if (!string.IsNullOrEmpty(view))
                {
                    AttachmentViewDetails(RSID);

                }

                if (!string.IsNullOrEmpty(delete))
                {
                    DeleteAttachmentDetails(RSID);

                }
                var AttachmentModel = GetAttachmentsDetails(RSID);

                return View(AttachmentModel);
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }




        public Attachments GetAttachmentsDetails(int RSID)
        {

            Attachments attachments = new Attachments();
            attachments.SidesRequest = _TPARequest.GetRec(RSID);

            var Request = _UCAContext.SidesTparesponses.Where(e => e.RequestForSeparationId == RSID)
                .Select(e => new
                {
                    TPAResponseId = e.TparesponseId
                }).FirstOrDefault();


            var TPAResponseAttachment = _UCAContext.SidesTparesponseattachments.Where(e => e.TparesponseId == Request.TPAResponseId).FirstOrDefault();


            List<SelectListItem> items = new List<SelectListItem>();
            foreach (var attachmentcode in _UCAContext.SidesAttachmentcodes)
            {
                if (TPAResponseAttachment != null)
                {
                    if (TPAResponseAttachment.DescriptionOfAttachmentCode == attachmentcode.AttachmentCodeId)
                        items.Add(new SelectListItem { Text = attachmentcode.AttachmentCode, Value = attachmentcode.AttachmentCodeId.ToString(), Selected = true });
                    else
                        items.Add(new SelectListItem { Text = attachmentcode.AttachmentCode, Value = attachmentcode.AttachmentCodeId.ToString() });
                }
                else
                {
                    items.Add(new SelectListItem { Text = attachmentcode.AttachmentCode, Value = attachmentcode.AttachmentCodeId.ToString() });
                }

            }

            attachments.SIDES_ATTACHMENTCODE = items;

            if (TPAResponseAttachment != null)
            {
                attachments.TypeofDocument = TPAResponseAttachment.TypeofDocument;
                if ((TPAResponseAttachment.UniqueAttachmentId == "") || (TPAResponseAttachment.UniqueAttachmentId == null))
                    attachments.UniqueAttachmentID = "01";
                else
                    attachments.UniqueAttachmentID = TPAResponseAttachment.UniqueAttachmentId;
                attachments.AttachmentSize = Convert.ToInt64(TPAResponseAttachment.AttachmentSize);
            }

            return attachments;

        }


        public void AttachmentSaveDetails(int RSID, IFormFile AttachmentUpload)
        {
            //if(AttachmentUpload == { .txt,.csv,.pdf})
            var Request = _UCAContext.SidesTparesponses.Where(e => e.RequestForSeparationId == RSID)
                .Select(e => new
                {
                    TPAResponseId = e.TparesponseId
                }).FirstOrDefault();

            var sidesTparesponse = _UCAContext.SidesTparesponseattachments.Where(e => e.TparesponseId == Request.TPAResponseId).FirstOrDefault();


            if (sidesTparesponse == null)
            {
                SidesTparesponseattachment sidesTparesponseattachment = new SidesTparesponseattachment
                {
                    TparesponseId = Request.TPAResponseId
                };


                _UCAContext.SidesTparesponseattachments.Add(sidesTparesponseattachment);
                _UCAContext.SaveChanges();


                sidesTparesponseattachment.TypeofDocument = HttpContext.Request.Form["TypeofDocument"].ToString();
                sidesTparesponseattachment.UniqueAttachmentId = HttpContext.Request.Form["UniqueAttachmentID"].ToString();
                sidesTparesponseattachment.ContentType = HttpContext.Request.Form["SIDESATTACHMENTCODE"].ToString();
                sidesTparesponseattachment.ContentType = AttachmentUpload.ContentType;
                string fileName = Path.GetFileName(AttachmentUpload.FileName);
                string contentType = AttachmentUpload.ContentType;
                using (MemoryStream ms = new MemoryStream())
                {
                    AttachmentUpload.CopyTo(ms)
;
                    sidesTparesponse.AttachmentData = ms.ToArray();
                }
                sidesTparesponseattachment.AttachmentSize = Convert.ToInt64(HttpContext.Request.Form["AttachmentSize"].ToString());
                _UCAContext.SidesTparesponseattachments.Update(sidesTparesponseattachment);
                _UCAContext.SaveChanges();


            }

            if (sidesTparesponse != null)
            {
                sidesTparesponse.TypeofDocument = HttpContext.Request.Form["TypeofDocument"].ToString();
                sidesTparesponse.UniqueAttachmentId = HttpContext.Request.Form["UniqueAttachmentID"].ToString();

                if (HttpContext.Request.Form["SIDESATTACHMENTCODE"].ToString() != "")
                    sidesTparesponse.DescriptionOfAttachmentCode = Convert.ToInt32(HttpContext.Request.Form["SIDESATTACHMENTCODE"].ToString());
                if (AttachmentUpload != null)
                {
                    sidesTparesponse.ContentType = AttachmentUpload.ContentType;
                    string fileName = Path.GetFileName(AttachmentUpload.FileName);
                    string contentType = AttachmentUpload.ContentType;
                    using (MemoryStream ms = new MemoryStream())
                    {
                        AttachmentUpload.CopyTo(ms)
;
                        sidesTparesponse.AttachmentData = ms.ToArray();
                    }
                    sidesTparesponse.AttachmentSize = Convert.ToInt64(HttpContext.Request.Form["AttachmentSize"].ToString());
                    _UCAContext.SidesTparesponseattachments.Update(sidesTparesponse);
                    _UCAContext.SaveChanges();
                }

            }

        }
        //if (ModelState.IsValid)
        //{
        //    string uniquefilefoldername;
        //    if (model.AttachmentUpload != null)
        //    {

        //        string DirPath = Path.Combine(_hostingEnvironment.WebRootPath, "Images");

        //        var data = model.AttachmentUpload;
        //        if (!Directory.Exists(DirPath))
        //        {
        //            Directory.CreateDirectory(DirPath);

        //        }
        //        model.AttachmentUpload.CopyTo(new FileStream(DirPath, FileMode.Create));

        //    }
        //}  


        [HttpGet]
        public ViewResult AttachmentViewDetails(int RSID)
        {
            var Request = _UCAContext.SidesTparesponses.Where(e => e.RequestForSeparationId == RSID)
         .Select(e => new
         {
             TPAResponseId = e.TparesponseId
         }).FirstOrDefault();

            var sidesTparesponse = _UCAContext.SidesTparesponseattachments.Where(e => e.TparesponseId == Request.TPAResponseId).FirstOrDefault();


            if (sidesTparesponse != null)
            {
                var uploadedfiles = _UCAContext.SidesTparesponseattachments.Where(e => e.TparesponseId.Equals(sidesTparesponse.TparesponseId)).First();
                if (uploadedfiles.AttachmentData != null)
                {
                    //byte[] binaryString = uploadedfiles.AttachmentData;
                    //string decodedString = Encoding.UTF8.GetString(binaryString);

SIDES/Areas/UI_SIDES/Views/SidesAttachments/SidesAttachmentsV.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model SIDES.ViewModels.Attachments
@using SIDES.Enums
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
          integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link href="~/css/Attachments.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.0/css/font-awesome.css"
          integrity="sha512-CB+XYxRC7cXZqO/8cP3V+ve2+6g6ynOnvJD6p4E4y3+wwkScH9qEOla+BTHzcwB4xKgvWn816Iv0io5l3rAOBA=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />

            <style>
     .form-control {
    display: block;
    width: 100%;
    height: 30px !important;
    padding: 0.375rem 0.75rem;
    font-size: 16px !important;
    font-weight: 500 !important;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da;
    border-radius: 0.25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;

     }

   input[type=file]:focus, input[type=checkbox]:focus, input[type=radio]:focus {
    outline: none !important;
    outline-offset: 0 !important;
}
}

lable {
    font-size: 18px;
}
.form_1 .input_end {
    display: flex;
    justify-content:center !important;
}

 </style>


</head>

<body>

    <div class="container">
        <div class="text-center">
            Response for SSN: @Model.SidesRequest.SSN Claim Number: @Model.SidesRequest.ClaimNumber Name @Model.SidesRequest.ClaimantLastName @Model.SidesRequest.ClaimantFirstName Effective Date :
            @Model.SidesRequest.ClaimEffectiveDate
        </div>
        <div style="display:none">
            <input type="text" id="RouteId" value="@Model.SidesRequest.RequestForSeparationId" />
        </div>
        <h3 class="text-center claim_heading">Attachments</h3>
        <form  enctype="multipart/form-data" class="form_1"  asp-controller="SidesAttachments" asp-action="SidesAttachmentsV" >
            <div class="form-group row">
                <label  asp-for="AttachmentUpload" for="formatAttachment" class="col-sm-3 col-form-label">
                    Attachment data
                </label>
                <div class="col-sm-9 input_end">
                     <input  class="form-control uploadedAttachments"  asp-for="AttachmentUpload"  name="AttachmentUpload" value="@Model.AttachmentUpload" >
                   @* <div class=""> 
                        <input  asp-for="AttachmentUpload" class="form-control custom-file-input" id="documentAttached" name="AttachmentUpload">
                        <label class="custom-file-label col-sm-7">Select...</label>
                        <input  asp-for="AttachmentUpload" type="file"/>
                        <label class="custom-file-label">Select...</label>

                     </div>*@
                </div>
            </div>
            <div class="form-group row">
                <label for="formatAttachment" class="col-sm-3 col-form-label">
                    What is the format of the attachment?
                </label>
                <div class="col-sm-9 input_end">
                    <select  disabled id="SIDESATTACHMENTCODE" name="SIDESATTACHMENTCODE" class="form-control" asp-items="@Model.SIDES_ATTACHMENTCODE"  >
                        <option value=""></option>
                       
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="documentAttached" class="col-sm-3 col-form-label">
                    What type of document is attached?
                </label>
                <div class="col-sm-9 input_end">
                    <input type="text" class="form-control" id="TypeofDocument"  name="TypeofDocument" value="@Model.TypeofDocument" readonly>
                </div>
            </div>
            <div class="form-group row">
                <label for="uniqueAttachment" class="col-sm-3 col-form-label">
                    Unique attachment id
                </label>
                <div class="col-sm-9 input_end">
                    <input type="text" class="form-control" id="uniqueAttachment" name="UniqueAttachmentID" value="@Model.UniqueAttachmentID" readonly>
                </div>
                
                <div class="container d-flex justify-content-center btn_del">
                    <div class="">
                        <input type="submit" name="view" value="view" class="save_btn">
                        <input type="submit" name="delete" value="delete" class="save_btn">
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <label for="attachmentSize" class="col-sm-3 col-form-label">
                    Attachment size
                </label>
                <div class="col-sm-9 input_end">
                    <input type="text" class="form-control attachmentSize" id="" name="AttachmentSize" value="@Model.AttachmentSize" readonly>
                </div>
            </div>
            <div class="row mt-3">
                <div class=" col-sm-6 mb-3 d-flex" id="Gotopage">
                    <label id="Gotopage" class="mx-2">Go To Page</label>
                     <span>
                     <select  name="Go to page" id="GotopageNext"  asp-items="Html.GetEnumSelectList<GoToNextPageEnum>()" onchange="GoToNextPageDDL()"  >
                   <option value="" >--Select--</option>
                  </select>
                  </span>

                </div>
                <div class="col-sm-6 prepare_btn">
                <input type="button" name="Cancel" value="Cancel" class="save_btn" onclick="CancelClick()">
                <input type="submit" name="Save" value="Save" class="save_btn" >
                <input type="submit" name="Next" value="Next" class="save_btn" >
               
             </div>

            </div>
        </form>
    </div>
      @if (ViewBag.Message != null)
    {
        <script type="text/javascript">
          
                alert("@ViewBag.Message");
         
        </script>
    }

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
            crossorigin="anonymous"></script>
</body>

</html>
<script src="~/js/GoToNextPage.js"> </Script> 

<script src="~/js/GoToNextPage.js"> </Script> 
<script>

   

     $(".uploadedAttachments").change(function () {
       var fileExtension = ['rtf', 'pdf', 'csv', 'txt', 'tiff'];
        if ($.inArray($(this).val().split('.').pop().toLowerCase(), fileExtension) == -1) {
            alert("Only formats are allowed : "+fileExtension.join(', '));
              $(this).val("");
        }
        else{
             
            
            if ($(this)[0].files[0].size > 2097152) {
                    alert("Try to upload file less than 2MB!");
                      $(this).val("");
                } 
                else if($(this)[0].files[0].size == 0){
                       alert("File is empty")
                        $(this).val("");
                }
                else {

                    var filename = $(this).val().split("\\").pop();
                   var ext =  $(this).val().split('.').pop().toUpperCase();
                    
                    var selectedvalue  ;
                     $("#SIDESATTACHMENTCODE > option").each(function() {
                           if(this.text == ext ){

                             selectedvalue = this.value;
                           }
                      });

                    $("#SIDESATTACHMENTCODE").val(selectedvalue);
                    $("#TypeofDocument").val(filename);
                    $('.attachmentSize').val($(this)[0].files[0].size);
                }

             
        }
    });
</script>