SIDES/Areas/UI_SIDES/Controllers/SidesPrepareController.cs
using MessagePack.Formatters;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.Differencing;
using Microsoft.VisualBasic;
using Newtonsoft.Json.Linq;
using SIDES.EFCoreModels.ScafffoldEntities.Persistance;
using SIDES.Interface;
using SIDES.Services;
using SIDES.ViewModels;
using System.Diagnostics;
using System.Security.Cryptography.X509Certificates;
using System.Xml.Linq;
using System.Xml.Serialization;
using static System.Net.Mime.MediaTypeNames;

namespace SIDES.Areas.UI_SIDES.Controllers
{
    [Area("UI_SIDES")]
    public class SidesPrepareController : Controller
    {
        private UCAContext _UCAContext;
        private ISidesTPARequest _TPARequest;
        private readonly IFlagRequestStatus flagRequestStatus;
        private readonly ILogger<SidesPrepareController> _logger;


        public SidesPrepareController(UCAContext uCAContext, ISidesTPARequest TPARequest,IFlagRequestStatus flagRequestStatus, ILogger<SidesPrepareController> logger)
        {
            this._UCAContext = uCAContext;
            this._TPARequest = TPARequest;
            this.flagRequestStatus = flagRequestStatus;
            _logger = logger;
        }

        [HttpGet]
        [Route("UI_SIDES/SidesPrepare/SidesPrepareV/{RSID}")]
        public IActionResult SidesPrepareV(int RSID)
        {
            try
            {
                GetPrepareDetails(RSID);
                var PrepareModel = GetPrepareDetails(RSID);
                return View(PrepareModel);
            }
            catch(Exception ex)
            {
                return View("Error");
            }

        }

      
        [Route("UI_SIDES/SidesPrepare/SidesPrepareV/{RSID}")]
        [HttpPost]
        public IActionResult SidesPrepareV(int RSID, string Save, string SendResponse,Prepare model)
        {
            try
            {
                if (!string.IsNullOrEmpty(Save))
                {
                    SavePrepareDetails(RSID);
                    flagRequestStatus.FlagRequestStatus(RSID, "Pending");
                }
                if (!string.IsNullOrEmpty(SendResponse))
                {
                    SavePrepareDetails(RSID);
                  //  flagRequestStatus.FlagRequestStatus(RSID, "Completed");
                    GenerateResponseXml(RSID);
                }
                var SidesPrepare = GetPrepareDetails(RSID);
                return View(SidesPrepare);
            }
            catch(Exception ex)
            {
                return View("Error");
            }
        }

        public Prepare GetPrepareDetails(int RSID)
        {
            var SidesTPAResponse = _UCAContext.SidesTparesponses.Where(e => e.RequestForSeparationId == RSID).FirstOrDefault();
            var Users = _UCAContext.AspnetUsers.Where(e => e.UserName == "gcosta")
               .Select(e => new
               {
                   UserId = e.UserId
               }).SingleOrDefault();
            //  var MemberShip = _UCAContext.AspnetMemberships.Where(e =>e.UserId == Users.UserId ).SingleOrDefault();

            Prepare PrepareModel = new Prepare();
            PrepareModel.SidesRequest = _TPARequest.GetRec(RSID);

            List<SelectListItem> items = new List<SelectListItem>();
            foreach (var Preparertypes in _UCAContext.SidesPreparertypes)
            {

                if (SidesTPAResponse.PreparerTypeCode == Preparertypes.PreparerTypeCode)
                    items.Add(new SelectListItem { Text = Preparertypes.PreparerType, Value = Preparertypes.PreparerTypeCode.ToString(), Selected = true });
                else
                    items.Add(new SelectListItem { Text = Preparertypes.PreparerType, Value = Preparertypes.PreparerTypeCode.ToString() });
            }
            PrepareModel.SIDES_PREPARERTYPE = items;


            items = new List<SelectListItem>();
            foreach (var Amendedresponses in _UCAContext.SidesAmendedresponses)
            {

                if (SidesTPAResponse.AmendedResponse == Amendedresponses.AmendedResponseValue)
                    items.Add(new SelectListItem { Text = Amendedresponses.AmendedResponse, Value = Amendedresponses.AmendedResponseValue.ToString(), Selected = true });
                else
                    items.Add(new SelectListItem { Text = Amendedresponses.AmendedResponse, Value = Amendedresponses.AmendedResponseValue.ToString() });
            }

            PrepareModel.SIDES_AMENDEDRESPONSE = items;

            PrepareModel.PreparerCompanyName = SidesTPAResponse.PreparerCompanyName;
            if (SidesTPAResponse.TparesponseId > 0)
            {

                PrepareModel.PreparerTelephoneNumberPlusExt = SidesTPAResponse.PreparerTelephoneNumberPlusExt;
                PrepareModel.PreparerContactName = SidesTPAResponse.PreparerContactName;
                PrepareModel.PreparerTitle = SidesTPAResponse.PreparerTitle;
                PrepareModel.PreparerFaxNbr = SidesTPAResponse.PreparerFaxNbr;
                PrepareModel.PreparerEmailAddress = SidesTPAResponse.PreparerEmailAddress;

            }
            else
            {
                //  PrepareModel.PreparerTelephoneNumberPlusExt = MemberShip.TelephoneNumber;
                //  PrepareModel.PreparerContactName = MemberShip.FirstName + MemberShip.LastName;
                //  PrepareModel.PreparerTitle = MemberShip.JobTitle;
                //  PrepareModel.PreparerFaxNbr = MemberShip.FaxNumber;
                //  PrepareModel.PreparerEmailAddress = MemberShip.Email
            }
            PrepareModel.AmendedResponseDescription = SidesTPAResponse.AmendedResponseDescription;
            return PrepareModel;
        }


        public void SavePrepareDetails(int RSID)
        {
            var SidesTPAResponse = _UCAContext.SidesTparesponses.Where(e => e.RequestForSeparationId == RSID).FirstOrDefault();




            SidesTPAResponse.PreparerTypeCode = HttpContext.Request.Form["SIDES_PREPARERTYPE"].ToString();
            SidesTPAResponse.PreparerCompanyName = HttpContext.Request.Form["PreparerCompanyName"].ToString();
            SidesTPAResponse.PreparerTelephoneNumberPlusExt = Request.Form["PreparerTelephoneNumberPlusExt"].ToString();
            SidesTPAResponse.PreparerContactName = Request.Form["PreparerContactName"].ToString();
            SidesTPAResponse.PreparerTitle = Request.Form["PreparerTitle"].ToString();
            SidesTPAResponse.PreparerFaxNbr = Request.Form["PreparerFaxNbr"].ToString();
            SidesTPAResponse.PreparerEmailAddress = Request.Form["PreparerEmailAddress"].ToString();
            SidesTPAResponse.AmendedResponse = Convert.ToInt32(Request.Form["SIDES_AMENDEDRESPONSE"]);
            SidesTPAResponse.AmendedResponseDescription = Request.Form["AmendedResponseDescription"];

            _UCAContext.SidesTparesponses.Update(SidesTPAResponse);
            _UCAContext.SaveChanges();

            flagRequestStatus.FlagRequestStatus(RSID, "Pending");





        }

        public void GenerateResponseXml(int RSID)
        {

            try
            {

                var oResponseList = new List<EmployerTPASeparationResponse>();
                var oRsponse = new EmployerTPASeparationResponse();


                //Load Request

                var SidesTPARequestModel = _UCAContext.SidesRequestforseparations.Where(e => e.RequestForSeparationId == RSID).FirstOrDefault();

                oRsponse.StateRequestRecordGUID = SidesTPARequestModel.StateRequestRecordGuid;
                oRsponse.BrokerRecordTransactionNumber = SidesTPARequestModel.BrokerRecordTransactionNumber;
                oRsponse.SSN = Convert.ToInt32(SidesTPARequestModel.Ssn);
                oRsponse.ClaimEffectiveDate = SidesTPARequestModel.ClaimEffectiveDate.Value.ToString("yyyy-MM-dd");
                oRsponse.ClaimNumber = SidesTPARequestModel.ClaimNumber;
                oRsponse.StateEmployerAccountNbr = SidesTPARequestModel.StateEmployerAccountNbr;
                oRsponse.EmployerName = SidesTPARequestModel.EmployerName;


                //Load Response
                var SidesResponse = _UCAContext.SidesTparesponses.Where(e => e.RequestForSeparationId == RSID).FirstOrDefault();


                //SidesResponse.aspx
                if (!String.IsNullOrEmpty(SidesResponse.CorrectedEmployerName.Trim()))
                {
                    oRsponse.CorrectedEmployerName = SidesResponse.CorrectedEmployerName;
                }
                if (!String.IsNullOrEmpty(SidesResponse.CorrectedStateEmployerAccountNbr.Trim()))
                {
                    oRsponse.CorrectedStateEmployerAccountNbr = SidesResponse.CorrectedStateEmployerAccountNbr;
                }
                if (!String.IsNullOrEmpty(SidesResponse.CorrectedFein.Trim()))
                {
                    oRsponse.CorrectedFEIN = SidesResponse.CorrectedFein;
                }

                //ÇlaimantInformation.aspx
                if (!String.IsNullOrEmpty(SidesResponse.OtherSsn.Trim()))
                {
                    oRsponse.OtherSSN = SidesResponse.OtherSsn;
                }
                if (!String.IsNullOrEmpty(SidesTPARequestModel.ClaimantLastName.Trim()))
                {
                    oRsponse.ClaimantLastName = SidesTPARequestModel.ClaimantLastName;
                }
                if (!String.IsNullOrEmpty(SidesTPARequestModel.ClaimantFirstName.Trim()))
                {
                    oRsponse.ClaimantFirstName = SidesTPARequestModel.ClaimantFirstName;
                }
                if (!String.IsNullOrEmpty(SidesTPARequestModel.ClaimantMiddleInitial.Trim()))
                {
                    oRsponse.ClaimantMiddleInitial = SidesTPARequestModel.ClaimantMiddleInitial;
                }
                if (!String.IsNullOrEmpty(SidesResponse.ClaimantNameWorkedAsForEmployer.Trim()))
                {

SIDES/Areas/UI_SIDES/Views/SidesPrepare/SidesPrepareV.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model SIDES.ViewModels.Prepare
@using SIDES.Enums
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
          integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link href="~/css/Prepare.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.0/css/font-awesome.css"
          integrity="sha512-CB+XYxRC7cXZqO/8cP3V+ve2+6g6ynOnvJD6p4E4y3+wwkScH9qEOla+BTHzcwB4xKgvWn816Iv0io5l3rAOBA=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />


    <style>
        .form-control {
            display: block;
            width: 100%;
            height: 30px !important;
            padding: 0.375rem 0.75rem;
            font-size: 16px !important;
            font-weight: 500 !important;
            line-height: 1.5;
            color: #495057;
            background-color: #fff;
            background-clip: padding-box;
            border: 1px solid #ced4da;
            border-radius: 0.25rem;
            transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
        }



        lable {
            font-size: 18px;
        }

        .form_1 .input_end {
            display: flex;
            justify-content: center !important;
        }
     
       

    </style>

</head>

<body>

    <div class="container">
        <div class="text-center">
            Response for SSN: @Model.SidesRequest.SSN Claim Number: @Model.SidesRequest.ClaimNumber Name WILSON @Model.SidesRequest.ClaimantLastName @Model.SidesRequest.ClaimantFirstName Effective Date :
            @Model.SidesRequest.ClaimEffectiveDate
        </div>
        <div style="display:none">
            <input type="text" id="RouteId" value="@Model.SidesRequest.RequestForSeparationId" />
        </div>
        <h3 class="text-center claim_heading">Preparer Details</h3>
        <form class="form_1" asp-controller="SidesPrepare" asp-action="SidesPrepareV">
            <div class="form-group row">
                <label for="providingResponse" class="col-sm-3 col-form-label">
                    Who is providing the response?
                </label>
                <div class="col-sm-9 input_end">
                    <select id="providingResponse" name="SIDES_PREPARERTYPE" class="form-control" asp-items="@Model.SIDES_PREPARERTYPE">
                        
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="companyPreparer" class="col-sm-3 col-form-label">
                    What is the name of the prepare's company?
                </label>
                <div class="col-sm-9 input_end">
                    <input type="text" class="form-control" id="companyPreparer" name="PreparerCompanyName" value="@Model.PreparerCompanyName">
                </div>
            </div>
            <div class="form-group row">
                <label for="telephonePreparer" class="col-sm-3 col-form-label">
                    What is the preparer's telephone number
                    with extension?
                </label>
                <div class="col-sm-9 input_end">
                    <input type="text" class="form-control" id="telephonePreparer" name="PreparerTelephoneNumberPlusExt" value="@Model.PreparerTelephoneNumberPlusExt">
                </div>
            </div>
            <div class="form-group row">
                <label for="namePreparer" class="col-sm-3 col-form-label">
                    What is the name of preparer?
                </label>
                <div class="col-sm-9 input_end">
                    <input type="text" class="form-control" id="namePreparer" name="PreparerContactName" value="@Model.PreparerContactName">
                </div>
            </div>
            <div class="form-group row">
                <label for="titlePreparer" class="col-sm-3 col-form-label">
                    What is the title of preparer?
                </label>
                <div class="col-sm-9 input_end">
                    <input type="text" class="form-control" id="titlePreparer" name="PreparerTitle" value="@Model.PreparerTitle">
                </div>
            </div>
            <div class="form-group row">
                <label for="faxNumber" class="col-sm-3 col-form-label">
                    What is preparer's Fax number?
                </label>
                <div class="col-sm-9 input_end">
                    <input type="text" class="form-control" name="PreparerFaxNbr" value="@Model.PreparerFaxNbr" id="faxNumber">
                </div>
            </div>
            <div class="form-group row">
                <label for="emailAddress" class="col-sm-3 col-form-label">
                    What is preparer's e-mail address?
                </label>
                <div class="col-sm-9 input_end">
                    <input type="text" class="form-control" id="emailAddress" value="@Model.PreparerEmailAddress" name="PreparerEmailAddress">
                </div>
            </div>
            <div class="form-group row">
                <label for="submittedResponse" class="col-sm-3 col-form-label">
                    Is this an amended response to a
                    previously submitted response?(new or additional information)
                </label>
                <div class="col-sm-9 input_end">
                    <select id="submittedResponse" class="form-control" name="SIDES_AMENDEDRESPONSE" asp-items="@Model.SIDES_AMENDEDRESPONSE">
                        
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="amendedResponse" class="col-sm-3 col-form-label">
                    What is the description of the amended
                    response?
                </label>
                <div class="col-sm-9 input_end">
                    <input type="text" class="form-control" id="amendedResponse" name="AmendedResponseDescription" value="@Model.AmendedResponseDescription">
                </div>
            </div>
              <div class="row mt-3">
                <div class=" col-sm-6 mb-3 d-flex" id="Gotopage">
                    <label id="Gotopage" class="mx-2">Go To Page</label>
                     <span>
                     <select  name="Go to page" id="GotopageNext"  asp-items="Html.GetEnumSelectList<GoToNextPageEnum>()" onchange="GoToNextPageDDL()"  >
                   <option value="" >--Select--</option>
                  </select>
                  </span>

                </div>
                <div class="col-sm-6 prepare_btn">
                <input type="button" name="Cancel" value="Cancel" class="save_btn" onclick="CancelClick()">
                <input type="submit" name="Save" value="Save" class="save_btn" >
                <input type="submit" name="SendResponse" value="SendResponse" class="save_btn" >
               
             </div>

            </div>

        </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
            crossorigin="anonymous"></script>
</body>

</html>
<script src="~/js/GoToNextPage.js"> </Script> 