SIDES/Areas/UI_SIDES/Controllers/SidesDischargeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using SIDES.EFCoreModels.ScafffoldEntities.Persistance;
using SIDES.Interface;
using SIDES.Services;
using SIDES.ViewModels;

namespace SIDES.Areas.UI_SIDES.Controllers
{
    [Area("UI_SIDES")]
    public class SidesDischargeController:Controller

    {
        private UCAContext _UCAContext;
        private ISidesTPARequest _TPARequest;
        private readonly IFlagRequestStatus flagRequestStatus;

        public SidesDischargeController(UCAContext uCAContext,ISidesTPARequest TPARequest, IFlagRequestStatus flagRequestStatus)
        {
            this._UCAContext = uCAContext;
            this._TPARequest = TPARequest;
            this.flagRequestStatus = flagRequestStatus;
        }

        [HttpGet]
        [Route("UI_SIDES/SidesDischarge/SidesDischargeV/{RSID}")]
        public IActionResult SidesDischargeV(int RSID)
        {
            try
            {
                var dischargeDetails = GetDischargeDetails(RSID);
                return View(dischargeDetails);
            }
            catch(Exception ex)
            {
                return View("Error");
            }
        }


        [HttpPost]
        [Route("UI_SIDES/SidesDischarge/SidesDischargeV/{RSID}")]
        public IActionResult SidesDischargeV(int RSID,string Save, string Next,DischargeDetails dischargeDetails)
        {
            try
            {
                if (!string.IsNullOrEmpty(Save))
                {
                    DischargeSaveDetails(RSID);
                    flagRequestStatus.FlagRequestStatus(RSID, "Pending");
                }
                if (!string.IsNullOrEmpty(Next))
                {
                    DischargeSaveDetails(RSID);
                    flagRequestStatus.FlagRequestStatus(RSID, "Pending");

                    // return Redirect("https://
                    //
                    // /ui_sides/sidesPrior/sidesPriorv/" + RSID);
                    return RedirectToAction("sidesPriorv", "sidesPrior", new { id = RSID, Area = "UI_SIDES" });
                }

                //  DischargeDetails Discahrge = GetDischargeDetails(RSID);

                var Discahrge = GetDischargeDetails(RSID);


                return View(Discahrge);
            }
            catch(Exception ex)
            {
                return View("Error");
            }
        }


        public DischargeDetails GetDischargeDetails(int RSID)
        {
            DischargeDetails dischargeDetails = new DischargeDetails();
            var SidesTPAResponse = _UCAContext.SidesTparesponses.Where(e => e.RequestForSeparationId == RSID).FirstOrDefault();

            dischargeDetails.sidesRequestModel = _TPARequest.GetRec(RSID);

            List<SelectListItem> items = new List<SelectListItem>();
            foreach (var Discharge in _UCAContext.SidesDischargereasoncodes)
            {
                if(SidesTPAResponse.DischargeReasonCode == Discharge.DischargeReasonCodeId)
                    items.Add(new SelectListItem { Text = Discharge.DischargeReasonCode, Value = Discharge.DischargeReasonCodeId.ToString(), Selected=true });
                else
                items.Add(new SelectListItem { Text = Discharge.DischargeReasonCode, Value = Discharge.DischargeReasonCodeId.ToString() });
            }

            dischargeDetails.SIDES_DISCHARGEREASONCODE = items;

            items = new List<SelectListItem>();
            foreach (var DischargePolicy in _UCAContext.SidesDischargepolicyawares)
            {
                if(SidesTPAResponse.DischargePolicyAwareExplanationCode == DischargePolicy.DischargePolicyAwareCode)
                    items.Add(new SelectListItem { Text = DischargePolicy.DischargePolicyAwareDesc, Value = DischargePolicy.DischargePolicyAwareCode.ToString() , Selected=true});
                else
                items.Add(new SelectListItem { Text = DischargePolicy.DischargePolicyAwareDesc, Value = DischargePolicy.DischargePolicyAwareCode.ToString() });
            }
            dischargeDetails.SIDES_DISCHARGEPOLICYAWARE = items;

        

            dischargeDetails.EmployerSepReasonComments = SidesTPAResponse.EmployerSepReasonComments;
            dischargeDetails.FinalIncidentReason = SidesTPAResponse.FinalIncidentReason;
            if (SidesTPAResponse.FinalIncidentDate.HasValue)
            {

                 ViewBag.FinalIncidentDate = SidesTPAResponse.FinalIncidentDate.Value.ToString("yyyy-MM-dd");
            }
            dischargeDetails.ViolateCompanyPolicyInd = SidesTPAResponse.ViolateCompanyPolicyInd;
            dischargeDetails.DischargePolicyAwareInd = SidesTPAResponse.DischargePolicyAwareInd;
            dischargeDetails.WhoDischargedName = SidesTPAResponse.WhoDischargedName;
            dischargeDetails.WhoDischargedTitle = SidesTPAResponse.WhoDischargedTitle;



            return dischargeDetails;
        }

        public void DischargeSaveDetails(int RSID)
        {
            var TPAResponse = _UCAContext.SidesTparesponses.Where(e => e.RequestForSeparationId == RSID).FirstOrDefault();

            if (TPAResponse != null)
            {
                TPAResponse.DischargeReasonCode = Convert.ToInt32(HttpContext.Request.Form["DischargeReasonCode"].ToString());
                TPAResponse.EmployerSepReasonComments = HttpContext.Request.Form["EmployerSepReasonComments"].ToString();
                TPAResponse.FinalIncidentReason = HttpContext.Request.Form["FinalIncidentReason"].ToString();
                TPAResponse.ViolateCompanyPolicyInd = HttpContext.Request.Form["ViolateCompanyPolicyInd"].ToString();
               
                if(HttpContext.Request.Form["FinalIncidentDate"].ToString() != "")
                TPAResponse.FinalIncidentDate = Convert.ToDateTime( HttpContext.Request.Form["FinalIncidentDate"].ToString());
                TPAResponse.DischargePolicyAwareInd = HttpContext.Request.Form["DischargePolicyAwareInd"].ToString();
                

                TPAResponse.DischargePolicyAwareExplanationCode = HttpContext.Request.Form["DischargePolicyAwareExplanationCode"].ToString();
                TPAResponse.WhoDischargedName = HttpContext.Request.Form["WhoDischargedName"].ToString();
                TPAResponse.WhoDischargedTitle = HttpContext.Request.Form["WhoDischargedTitle"].ToString();

                _UCAContext.SidesTparesponses.Update(TPAResponse);
                _UCAContext.SaveChanges();




            }
        }
    }
}

SIDES/Areas/UI_SIDES/Views/SidesDischarge/SidesDischargeV.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model SIDES.ViewModels.DischargeDetails
@using SIDES.Enums
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
          integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
   
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.0/css/font-awesome.css"
          integrity="sha512-CB+XYxRC7cXZqO/8cP3V+ve2+6g6ynOnvJD6p4E4y3+wwkScH9qEOla+BTHzcwB4xKgvWn816Iv0io5l3rAOBA=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
 <link href="~/css/Discharge.css" rel="stylesheet">
 <style>
     .form-control {
    display: block;
    width: 100%;
    height: 30px !important;
    padding: 0.375rem 0.75rem;
    font-size: 16px !important;
    font-weight: 500 !important;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da;
    border-radius: 0.25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}

lable {
    font-size: 18px;
}
.form_1 .input_end {
    display: flex;
    justify-content:center !important;
}

 </style>
</head>

<body>

    <div class="container">
        <div class="text-center">
            Response for SSN: @Model.sidesRequestModel.SSN Claim Number: @Model.sidesRequestModel.ClaimNumber Name @Model.sidesRequestModel.ClaimantLastName @Model.sidesRequestModel.ClaimantFirstName Effective Date :
            @Model.sidesRequestModel.ClaimEffectiveDate
        </div>
        <div style="display:none">
            <input type="text" id="RouteId" value="@Model.sidesRequestModel.RequestForSeparationId" />
        </div>
        <h3 class="text-center claim_heading">Claimant - Discharge Details</h3>
        <form class="form_1" method="post" asp-controller="SidesDischarge" asp-action="SidesDischargeV">
            <div class="form-group row">
                <label for="claimantSeparation" class="col-sm-3 col-form-label">
                    What is the reason the claimant was
                    discharged from employment?
                </label>
                <div class="col-sm-9 input_end">
                    <select id="claimantSeparation" name="DischargeReasonCode" class="form-control" asp-items="@Model.SIDES_DISCHARGEREASONCODE">
                        
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="returnWork" class="col-sm-3 col-form-label">
                    Explain why the claimant is no longer
                    employmed; or indicate if and what additional information
                    on the claim will be faxed or emailed to the state; or enter additional information relevant to
                    the claim
                </label>
                <div class="col-sm-9 input_end">
                    <textarea rows="4" cols="50" name="EmployerSepReasonComments" id="notClaim">@Model.EmployerSepReasonComments</textarea>
                </div>
            </div>
            <div class="form-group row">
                <label for="returnDate" class="col-sm-3 col-form-label">
                    What was the final incident that caused the
                    discharged?
                </label>
                <div class="col-sm-9 input_end">
                    <input type="text" class="form-control" id="text-form-btn" name="FinalIncidentReason" value="@Model.FinalIncidentReason">
                </div>
            </div>
            <div class="form-group row">
                <label for="availableHours" class="col-sm-3 col-form-label">
                    What was the date of the final
                    incident?
                </label>
                <div class="col-sm-9 input_end">
                    <input type="date" class="form-control" id="returnDate" name="FinalIncidentDate" value="@ViewBag.FinalIncidentDate">
                </div>
            </div>
            <div class="form-group row">
                <label for="notClaim" class="col-sm-3 col-form-label">
                    Did the claimant violate company
                    policy?
                </label>
                <div class="col-sm-9 input_end">
                    <select id="VoilateCompanyRules" class="form-control" name="ViolateCompanyPolicyInd">
                        @{
                            if (Model.ViolateCompanyPolicyInd == "Y"){
                            <option value="Y" selected>Yes</option>
                            <option value="N">No</option>
                            }
                            else if (Model.ViolateCompanyPolicyInd == "N"){
                                <option value="Y" >Yes</option>
                                <option value="N" selected>No</option>
                            }
                            else{
                                <option value="Y" selected>Yes</option>
                                <option value="N">No</option>
                            }
                        }
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="typeOfLabour" class="col-sm-3 col-form-label">
                    Was the claimant aware of the policy or
                    unacceptable behaviour that contributed to the
                    discharge?
                </label>
                <div class="col-sm-9 input_end">
                    <select id="PolicyAwareness" class="form-control" name="DischargePolicyAwareInd">
                        @{
                            if (Model.DischargePolicyAwareInd == "Y") {
                                <option value="Y" selected>Yes</option>
                                <option value="N">No</option>
                            }
                            else if (Model.DischargePolicyAwareInd == "N")
                            {
                                <option value="Y">Yes</option>
                                <option value="N" selected>No</option>
                            }
                            else{
                                <option value="Y" selected>Yes</option>
                                <option value="N">No</option>
                            }
                        }
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="earnedWages" class="col-sm-3 col-form-label">
                    How was the claimant aware of the policy or
                    unacceptable behaviour that contributed to the
                    discharge?
                </label>
                <div class="col-sm-9 input_end">
                    <select id="typeOfLabour" class="form-control" name="DischargePolicyAwareExplanationCode" asp-items="@Model.SIDES_DISCHARGEPOLICYAWARE">
                      
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="weekWorkedAailable" class="col-sm-3 col-form-label">
                    What is the name of the person who
                    discharged the claimant?
                </label>
                <div class="col-sm-9 input_end">
                    <textarea rows="4" cols="50" name="WhoDischargedName" id="notClaim">@Model.WhoDischargedName</textarea>
                </div>
            </div>
            <div class="form-group row">
                <label for="weeksWorked" class="col-sm-3 col-form-label">
                    what is the title of the person who
                    discharged the claimant?
                </label>
                <div class="col-sm-9 input_end">
                    <textarea rows="4" cols="50" name="WhoDischargedTitle" id="notClaim">@Model.WhoDischargedTitle</textarea>
                </div>
            </div>
            <div class="row mt-3">
                <div class=" col-sm-6 mb-3 d-flex" id="Gotopage">
                    <label id="Gotopage" class="mx-2">Go To Page</label>
                     <span>
                     <select  name="Go to page" id="GotopageNext"  asp-items="Html.GetEnumSelectList<GoToNextPageEnum>()" onchange="GoToNextPageDDL()"  >
                   <option value="" >--Select--</option>
                  </select>
                  </span>

                </div>
                <div class="col-sm-6 prepare_btn">
                <input type="button" name="Cancel" value="Cancel" class="save_btn" onclick="CancelClick()">
                <input type="submit" name="Save" value="Save" class="save_btn" >
                <input type="submit" name="Next" value="Next" class="save_btn" >
               
             </div>

            </div>
           
        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
            crossorigin="anonymous"></script>
</body>

</html>



<script src="~/js/GoToNextPage.js"> </Script>   
    <script>
     $(document).ready(function(){
         $("#VoilateCompanyRules").change(function () {
            if ($(this).val() == "N") {
               
                $("#PolicyAwareness").val("N");
              
            } else {
                 $("#PolicyAwareness").val("Y");
            }
        });
     });
</script>